### ISSUE TITLE
Find latest TwinCAT version

### ISSUE THREAD

**Issue by Beidendorfer** [tcunit/TcUnit-Runner#15]
The installed TwinCat versions are listed in the interface` ITcRemoteManager remoteManager.Versions`.
In the current sorting the last version is at position `remoteManager.Versions[0]`

In order not to rely on the sorting the last version should be determined from the interface `remoteManager.Versions`

maybe with the Versions class?

![image](https://user-images.githubusercontent.com/40072981/102712007-311aee00-42be-11eb-9bd4-27d1b2d0fa30.png)

**Comment by sagatowski** [comment]
I think the versions class would be suitable for this. @Beidendorfer I'll assign this to you, I hope it's fine!

**Comment by sagatowski** [comment]
Solved by PR #16.
