### ISSUE TITLE
Expected and Actual values in Error Details

### ISSUE THREAD

**Issue by kumaraswamygaviyappa** [tcunit/TcUnit-Runner#17]
After Jenkins job is executed, is that possible to add **Expected** and **Actual values** in **Error Details** which shows only **Error Message**.

**Comment by sagatowski** [comment]
Hi @kumaraswamygaviyappa !
I'm not sure I follow along. The Expected and Actual values + Error message is already written to the xUnit-XML file, so the xUnit Jenkins-plugin should be able to see it?

**Comment by kumaraswamygaviyappa** [comment]
Hi @sagatowski ,
Yes, in my opinion, its good to see the Expected and Actual values + Error message in Test Result page of Jenkins job.

**Comment by sagatowski** [comment]
Hey!

What message you see in the test result page of Jenkins is not decided by TcUnit, but by which plugin you use.
TcUnit reports all data in the XML-file, so Jenkins can access it. Then what data is presented in Jenkis is not decided by TcUnit.

**Comment by kumaraswamygaviyappa** [comment]
Hi @sagatowski ,

Thanks for the explanation. 
Is that possible to update XML file with Expected and Actual values + Error message. 
I could see only **message** in the xml file. Am i missing something? :( 
![image](https://user-images.githubusercontent.com/10028131/105329868-ec8eb500-5bd1-11eb-9487-a6964b4a9db0.png)

**Comment by sagatowski** [comment]
Hi @kumaraswamygaviyappa!
Ah yes, you are right! Now I remember. I created this picture to show what TcUnit+TcUnit-Runner supports:
https://user-images.githubusercontent.com/33381702/71117164-e7dd1d80-21d5-11ea-840a-9aebdd3dbb72.png
This is according to the xUnit XML standard:
https://wiki.yoctoproject.org/wiki/QA/xUnit_XML_Template

In this standard, the assert actual and expected values are not included for some reason!
