### ISSUE TITLE
Explicit execution of static analysis via the AI

### ISSUE THREAD

**Issue by kumaraswamygaviyappa** [tcunit/TcUnit-Runner#18]
Would it be possible to include **RunStaticAnalysis** in  **TcUnit-Runner arguments/options** when there are no BuildError

The use case as mentioned in [TcUnit/issues/93](https://github.com/tcunit/TcUnit/issues/93).
1. The [USB license stick](https://alltwincat.com/2017/10/12/twincat-static-code-analysis/) in the server. Test server architecture is as mentioned [Example_2_-_Separate_Jenkins_master_Jenkins_agent](https://tcunit.org/tcunit-runner-user-manual/#Example_2_-_Separate_Jenkins_master_Jenkins_agent)
2. Developers pushes the code to server, static analysis will be triggered by Jenkins in the Server.

I tested this in [tcunit/ExampleProjects](https://github.com/tcunit/ExampleProjects) by adding below code and it worked well.

![image](https://user-images.githubusercontent.com/10028131/105367790-1d3a1300-5c01-11eb-8f40-a769f12599da.png)

If this included in **TcUnit-Runner** , it will be a All in one Framework :)

**Comment by sagatowski** [comment]
This should be in a separate tool, that can be included in your Jenkins pipeline as a separate step after execution of the tests. So you basically create a pipeline, where you have the TcUnit-Runner running, and then (depending on result), the Static Code analysis tool.

I wrote a very basic implementation of a tool like that several years ago that's also MIT open-source, and with a bunch of documentation to it. It's available at:
https://github.com/sagatowski/TcStaticAnalysisLoader

**Comment by kumaraswamygaviyappa** [comment]
Hi @sagatowski ,
Yes, i used same implementation to learn TwinCat programming/Jenkins and tested RunStaticAnalysis.
My understanding is, when Jenkins pipeline is implemented, visual studio process will be enabled two times.

1. visual studio process will build the project if no errors RunStaticAnalysis.
2. visual studio process initiated by TcUnit-Runner which builds the project and runs Tcunit frame work.

Is that possible to merge. Is my understanding correct?

**Comment by sagatowski** [comment]
It depends on what your definition of "to merge" is.
If it means to run as a single workflow in Jenkins, then yes.

**Comment by sagatowski** [comment]
Have you experimented with pipelines in Jenkins?
https://www.jenkins.io/pipeline/getting-started-pipelines/

I think you could probably put these two programs into a pipeline.

**Comment by kumaraswamygaviyappa** [comment]
@sagatowski 

I could achieve this using pipeline. Thank you for the suggestion.

![image](https://user-images.githubusercontent.com/10028131/107539651-77f1d980-6bc5-11eb-9afe-2c75e5084dc1.png)

VS is invoked 3 times. In Stages **Build**,**TE1200** and **Unit Testing**. I used [TcStaticAnalysisLoader](https://github.com/sagatowski/TcStaticAnalysisLoader ) here.
And again VS is invoked by **TcUnit-Runner** in stage **Report Analysis**

I feel this not the efficient way but it's working as i wanted.
