### ISSUE TITLE
TcUnit-Runner Microsoft Azure DevOps

### ISSUE THREAD

**Issue by runtimevic** [tcunit/TcUnit-Runner#22]
Hello Jakob Sagatowski,
Thank you very much for sharing and developing with Beckhoff twincat Test driven development (TDD), 
I don't know if it would be possible instead of using Jenkins that it was with Azure Devops ?.
I am interested in this development if there was a TcUnit-Runner-Azure DevOps, 
I don't know if you have any interest in doing it?
Thank you so much for everything.

**Comment by sagatowski** [comment]
Hi @runtimevic!
I'm happy you find this project useful.

TcUnit-Runner works just fine with most automation software, including Azure DevOps.
Jenkins was just used as an example.
There are several users that have succesfully used TcUnit-Runner together with Azure Devops.
https://tcunit.org/frequently-asked-questions/?Display_FAQ=968

If you have the time, I'd be happy if you could write some documentation/user manual of your findings with Azure Devops, and then I could upload that on the website if others would want to do the same thing.

**Comment by sagatowski** [comment]
Hey @larsrod81! The website for TcUnit-Runner is currently being moved to one that is generated automatically. Please see here: https://github.com/tcunit/TcUnit-Runner/tree/master/docs
