### ISSUE TITLE
Exit process with an exit code depending on test-results

### ISSUE THREAD

**Issue by densogiaichned** [tcunit/TcUnit-Runner#26]
Currently , the `TcUnit-Runner` process is exiting with exitcode `0` - `RETURN_SUCCESSFULL`, unless a error occurred.  
The process should return an exiting code, depending on the test-results, i.e. 
* all tests ok: `RETURN_SUCCESSFULL`
* at least on test failed: `RETURN_TESTS_FAILED `
* no test result at all (possible bug):  `RETURN_ERROR_NO_TEST_RESULTS`

This would mimic the same behaviour as other test-suites offer, i.e. `VsTest`, i.e. in `GitHub Actions`.

**Comment by sagatowski** [comment]
Solved in commit bae4e18.
Thanks for your contribution @densogiaichned!
