### ISSUE TITLE
Lacking flexibility on ErrorList entry processing for newer VS environments

### ISSUE THREAD

**Issue by davidlonghowick** [tcunit/TcUnit-Runner#4]
TwinCAT projects created in Visual Studio versions newer than 2013 don't have default ErrorList order setting, which means that the ErrorList entries are not ordered in the expected format for TcUnit-runner to parse (TcUnitResultCollector ln 122-375).

**Comment by sagatowski** [comment]
Excellent catch! Do you know if it's possible to change the errorlist ordering by the DTE?

**Comment by sagatowski** [comment]
I've tested this and can confirm that the same behaviour occurs with VS2013. VS2013 simply just remembers the last sorting-setting that you have for the errorlist, and applies that to the list that gets returned.

@davidlonghowick If you can find a nice solution to this it would be appreciated.

**Comment by sagatowski** [comment]
I haven't managed to find any way to sort the data coming directly from the DTE, so I guess we need to apply the same sorting that visual studio does when clicking the "Description"-field.
This should be done on either the:
`ErrorItems errorItems`
or the
`List<ErrorList.Error> errors`

**Comment by sagatowski** [comment]
@davidlonghowick - I've done a fix, can you do a clone of the repo, compile the TcUnit-Runner and see whether it fixes the issue?

**Comment by davidlonghowick** [comment]
> 
> 
> @davidlonghowick - I've done a fix, can you do a clone of the repo, compile the TcUnit-Runner and see whether it fixes the issue?

Tested and it appears resolved. Appreciate the quick response, currently using this on an Azure VM for a CI pipeline and really needed the unit testing running!

**Comment by sagatowski** [comment]
@davidlonghowick Great that it seems to fix the issue! I'll do some more testing and then do a formal release during the weekend.
Thanks for reporting this issue!

**Comment by sagatowski** [comment]
Solved in 533a21a. Created new release (0.9.1).
