### ISSUE TITLE
Add feature to optionally specify a directory for saving test result

### ISSUE THREAD

**Issue by ahuca** [tcunit/TcUnit-Runner#44]
There might be a need to save the test result in a specific directory relative to the Visual Studio solution being run. This is useful for gathering test results neatly together in the same place. One particular use case I encountered was when using this tool together with Bitbucket pipeline, which requires test results to be inside directories named according to a set of supported names. See more info about that at https://support.atlassian.com/bitbucket-cloud/docs/test-reporting-in-pipelines/.

I could add a script within the pipeline to move the test results manually afterwards to my desired path, but having this as a feature in the TcUnit-Runner is a much cleaner solution.

**Comment by sagatowski** [comment]
This project is archived. Replacement for it is in the works.
