### ISSUE TITLE
Testsuite failures are not updated

### ISSUE THREAD

**Issue by slimeth** [tcunit/TcUnit-Runner#48]
I was using [AdvancedExampleProject](https://github.com/tcunit/ExampleProjects/tree/master/AdvancedExampleProject) and the latest released TcUnitRunner (0.9.3.0). 

I changed one test to fail and noticed that the xUnit result for the test suite had still 0 failures.

`<testsuite id="4" name="PRG_TEST.fbDiagnosticMessageTimeStampParser_Test" tests="2" failures="0">`
`    <testcase name="TestWithTimestampZeroTimeExpectCurrentTime" assertions="0" classname="PRG_TEST.fbDiagnosticMessageTimeStampParser_Test" status="PASS" />`
`    <testcase name="TestWithValidTimestampExpectSameTimestamp" assertions="0" classname="PRG_TEST.fbDiagnosticMessageTimeStampParser_Test" status="FAIL">`
`        <failure message="Test 'TimeStamp zero time' failed" type="BOOL" />`
`    </testcase>`
`</testsuite>`

**Comment by sagatowski** [comment]
What RELEASED version of TcUnit were you running?

**Comment by sagatowski** [comment]
There is no TcUnit 1.2.1.0.
Please run an officially released version.

**Comment by slimeth** [comment]
You're right. Idk what happened. I might have compiled the TcUnit library from the repository. With 1.2.0.0 it worked properly.
