### ISSUE TITLE
TcUnit release 1.3.0.0 seems to broke the old TcUnit-Runner documentation

### ISSUE THREAD

**Issue by ahuca** [tcunit/TcUnit-Runner#52]
**Describe the bug**
TcUnit-Runner documentation website has been broken.

**To Reproduce**
Go to [TcUnit-Runner](https://github.com/tcunit/TcUnit-Runner), and click on "user manual" hyperlinked text in the [`README.md`](https://github.com/tcunit/TcUnit-Runner/blob/24296683f31ca0380507da052658e7dbf5348675/README.md), which is the same as clicking link https://tcunit.org/tcunit-runner-user-manual/.

**Screenshots**
![image](https://github.com/tcunit/TcUnit/assets/22328056/2caa2375-c945-46f1-8ac0-4902f4ddacb2)

**Comment by sagatowski** [comment]
This project is archived. Replacement for it is in the works.
