### ISSUE TITLE
README link to user manual returns 404

### ISSUE THREAD

**Issue by shanereetz** [tcunit/TcUnit-Runner#53]
**Describe the bug**
The URL for the User Manual appears to be incorrect in the README.md in the root of the repo, or file permissions may be preventing other users from viewing it.

**To Reproduce**
Clicking the "user manual" link or attempting to visit the URL (https://tcunit.org/tcunit-runner-user-manual/) manually results in a GitHub pages 404 File Not Found

**Expected behavior**
Expected behavior is that this link would redirect to external docs or perhaps to the docs README [here](https://github.com/tcunit/TcUnit-Runner/blob/master/docs/readme.md), which appears to have the info I was looking for.

My assumption is this is just an outdated link from a webpage migration.

**Screenshots**
![Screenshot 2024-02-08 113814](https://github.com/tcunit/TcUnit-Runner/assets/88599267/4f3294d0-cb40-4d3f-a4dd-612ee9b2e835)

**Software versions**
n/a

**Run environment**
n/a

**Additional context**
n/a

**Comment by sagatowski** [comment]
This project is archived. Replacement for it is in the works.
